<a href="https://colab.research.google.com/github/SrikarNagavelli/2303A51772_Batch12/blob/main/DataScience_lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# Marks array (Math, Physics, Chemistry for 5 students)
marks = np.array([
    [78, 85, 90],
    [92, 88, 76],
    [67, 73, 70],
    [89, 94, 91],
    [56, 60, 65]
])
print("Original Marks Array:\n", marks)


Original Marks Array:
 [[78 85 90]
 [92 88 76]
 [67 73 70]
 [89 94 91]
 [56 60 65]]


In [ ]:
print("\nAverage marks of each student:", np.mean(marks, axis=1))
print("Minimum marks of each student:", np.min(marks, axis=1))
print("Maximum marks of each student:", np.max(marks, axis=1))

print("\nMarks of 3rd student (index 2):", marks[2])

print("\nStudents with any subject > 80:\n", marks[np.any(marks > 80, axis=1)])


Average marks of each student: [84.33333333 85.33333333 70.         91.33333333 60.33333333]
Minimum marks of each student: [78 76 67 89 56]
Maximum marks of each student: [90 92 73 94 65]

Marks of 3rd student (index 2): [67 73 70]

Students with any subject > 80:
 [[78 85 90]
 [92 88 76]
 [89 94 91]]


In [ ]:

subject_wise = marks.T
print("\nSubject-wise Marks (Transposed):\n", subject_wise)

print("Average marks per subject:", np.mean(subject_wise, axis=1))


Subject-wise Marks (Transposed):
 [[78 92 67 89 56]
 [85 88 73 94 60]
 [90 76 70 91 65]]
Average marks per subject: [76.4 80.  78.4]


In [ ]:

data = {
    'Student': ['S1', 'S2', 'S3', 'S4', 'S5'],
    'Math': marks[:, 0],
    'Physics': marks[:, 1],
    'Chemistry': marks[:, 2]
}

df = pd.DataFrame(data)
print("\nOriginal DataFrame:\n", df)



Original DataFrame:
   Student  Math  Physics  Chemistry
0      S1    78       85         90
1      S2    92       88         76
2      S3    67       73         70
3      S4    89       94         91
4      S5    56       60         65


In [ ]:

df['Average'] = df[['Math', 'Physics', 'Chemistry']].mean(axis=1)

df['Passed'] = df['Average'] >= 80

print("\nDataFrame with 'Average' and 'Passed' columns:\n", df)



DataFrame with 'Average' and 'Passed' columns:
   Student  Math  Physics  Chemistry    Average  Passed
0      S1    78       85         90  84.333333    True
1      S2    92       88         76  85.333333    True
2      S3    67       73         70  70.000000   False
3      S4    89       94         91  91.333333    True
4      S5    56       60         65  60.333333   False


In [ ]:
# Students with average > 80
high_scorers = df[df['Average'] > 80]
print("\nStudents with Average > 80:\n", high_scorers)
overall_avg = df[['Math', 'Physics', 'Chemistry']].mean()
print("\nSubject-wise Overall Averages:\n", overall_avg)


Students with Average > 80:
   Student  Math  Physics  Chemistry    Average  Passed
0      S1    78       85         90  84.333333    True
1      S2    92       88         76  85.333333    True
3      S4    89       94         91  91.333333    True

Subject-wise Overall Averages:
 Math         76.4
Physics      80.0
Chemistry    78.4
dtype: float64
